### ISSUE TITLE
Configure the go app to run

### ISSUE THREAD

**Issue by LHTNGUYEN** [LHTNGUYEN/simple-fortune-cookie#1]
- Install go on your cloud instance
- Investigate dependencies
- Put dependencies in go.mod
- Build with go build
- Run both the frontend and backend with go run ..
- Familiarize yourself with the application (frontend and backend, try to add a cookie and re-run the backend)

**Comment by vitus1** [comment]
Made it run, added a cookie, tried to rerun backend, which made the cookies disappaer

**Comment by vitus1** [comment]
Have been run
